optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 4096
  save_model: true
  loss: pairwise
  test_step: 3
  reproducible: true
  seed: 2023
  patience: 5

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf
  name: amazon

model:
  name: lightgcn_int
  # general parameters here
  keep_rate: 1.0
  embedding_size: 32
  intent_num: 128
  # dataset-specific parameters here
  layer_num: 3
  reg_weight: 1.0e-7
  kd_weight: 1.0e-2
  kd_temperature: 0.2
  kd_int_weight: 1.0e-2
  kd_int_temperature: 0.2
  # for amazon
  amazon:
    layer_num: 3
    reg_weight: 1.0e-7
    kd_weight: 1.0e-2
    kd_temperature: 0.2
#    kd_int_weight: 2.0e-2
    kd_int_weight_1: 2.0e-2
    kd_int_temperature: 0.2

  # for yelp
  yelp:
    layer_num: 3
    reg_weight: 1.0e-7
    kd_weight: 1.0e-2
    kd_temperature: 0.2
#    kd_int_weight: 1.0e-2
    kd_int_weight_1: 1.0e-2
    kd_int_temperature: 0.2
    kd_int_weight_2: 5.0e-4
    kd_int_weight_3: 1.0e-4

  # for movie
  movie:
    layer_num: 3
    reg_weight: 1.0e-6
    kd_weight: 1.0e-3
    kd_temperature: 0.2
#    kd_int_weight: 3.0e-2
    kd_int_weight_1: 3.0e-2
    kd_int_temperature: 0.2
    kd_int_weight_2: 5.0e-4
    kd_int_weight_3: 1.0e-4
